name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run unit tests with Maven
      run: mvn clean verify --batch-mode

  base-image-snyk-scan:
    needs: build-and-run-tests
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set execute permission for mvnw
      run: chmod +x mvnw  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t elisiejus-app-image .  

    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: elisiejus-app-image
        args: --file=Dockerfile --severity-threshold=high --sarif-file-output=snyk.sarif

    - name: Upload Snyk SARIF report to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif

  vulnerabilities-snyk-scan:
    needs: base-image-snyk-scan
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
      - uses: actions/checkout@master
      
      - name: Set execute permission for mvnw
        run: chmod +x mvnw

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-17@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test --sarif-file-output=snyk.sarif

      - name: Verify SARIF file exists
        run: ls -l snyk.sarif || echo "SARIF file not found!"

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif        

  push-to-artifactory:
     needs: vulnerabilities-snyk-scan
     runs-on: ubuntu-latest
     
     steps:
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
         image: elisiejus11/demo-project
         push: true
         tags: elisiejus11/githubaction:latest
