name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run unit tests with Maven
      run: mvn clean verify --batch-mode

  build-scan-push:
    needs: run-tests
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set execute permission for mvnw
      run: chmod +x mvnw  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t elisiejus11/demo-project:latest . 

    - name: Upload Docker Image Artifact
      uses: actions/upload-artifact@v3
      with:
        name: demo-project-image
        path: demo-project.tar   

    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: elisiejus11/demo-project:latest
        args: --file=Dockerfile --severity-threshold=high --sarif-file-output=snyk.sarif

    - name: Upload Snyk SARIF report to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif     

    - name: Download Docker Image Artifact
      uses: actions/download-artifact@v3
      with:
        name: demo-project-image
 
    - name: Load Docker Image
      run: |
        docker load < demo-project.tar       

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
 
    - name: Push Docker Image
      run: |
        docker push elisiejus11/demo-project:latest
