name: Post-deploy check

on:
  workflow_run:
    workflows: [ "Deploy" ]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  get-ip-and-check-health:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecr-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download JSON file from S3
        run: |
          aws s3 cp s3://elisiejus-output-bucket/outputs.json outputs.json

      - name: Make cURL request
        run: |
          PUBLIC_IP=${{ steps.extract-ip.outputs.public_ip }}
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://$PUBLIC_IP:8080/actuator/health)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Health check failed with HTTP status: $RESPONSE"
            exit 1
          else
            echo "Health check passed with HTTP status: $RESPONSE"
          fi