name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecr-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init -input=false -force-copy
        working-directory: terraform

      - name: Terraform State List
        run: terraform state list
        working-directory: terraform

      - name: Terraform Refresh
        run: terraform refresh
        working-directory: terraform   

      - name: Terraform State List after refresh
        run: terraform state list
        working-directory: terraform   
   
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: terraform
        env:
          TF_VAR_public_key: ${{ secrets.EC2_PUBLIC_KEY }}
